# Basic
title: Peng Zhao
subtitle: Simple is difficult.
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
welcome_message: Posts about my recent study will be published soon.
description: hi, I'm a PhD student in Shanghai, with focus on spatial-temporal compution.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
# nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 1908663553
    github: geo-roc
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: peng.zhao@tongji.edu.cn

# Google Analytics
# ga:
    # id: your_ga_id
    # host: your_host
